version: '3.7'
services:

  frontend:
    image: ${DOCKER_REGISTRY}/${DOCKER_FRONTEND_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    restart: always
    container_name: todo-skill-up-frontend
    command: ["yarn", "start"]
    environment:
      APP_VERSION: ${DOCKER_IMAGE_VERSION}
      APP_BASE_URL: ${APP_BASE_URL}
      WS_APP_URL: ${WS_APP_URL}
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  api:
    image: ${DOCKER_REGISTRY}/${DOCKER_API_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    restart: always
    container_name: todo-skill-up-api
    command: ["yarn", "start"]
    environment:
      APP_PORT: 8081
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGGING: ${TYPEORM_DB_LOGGING}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TOKEN_SECRET_WORD: ${JWT_SECRET_WORD}
      TOKEN_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    depends_on:
      - mariadb
      - redis
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  ws:
    image: ${DOCKER_REGISTRY}/${DOCKER_WS_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    restart: always
    container_name: todo-skill-up-ws
    command: ["yarn", "run", "start:prod"]
    environment:
      APP_PORT: 8088
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGGING: ${TYPEORM_DB_LOGGING}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TOKEN_SECRET_WORD: ${JWT_SECRET_WORD}
    depends_on:
      - mariadb
      - redis
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  nginx:
    image: ${DOCKER_REGISTRY}/${DOCKER_NGINX_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    restart: always
    container_name: todo-skill-up-nginx
    ports:
      - ${NGINX_PORT}:80
    environment:
      NGINX_PORT: ${NGINX_PORT}
    depends_on:
      - frontend
      - swagger
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  swagger:
    image: ${DOCKER_REGISTRY}/${DOCKER_SWAGGER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    restart: always
    container_name: todo-skill-up-swagger
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  redis:
    image: redis:7.0.0
    restart: always
    container_name: todo-skill-up-redis
    ports:
      - 127.0.0.1:${REDIS_OUTER_PORT}:${REDIS_PORT}
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  mariadb:
    image: mariadb:10.6.14
    restart: always
    container_name: todo-skill-up-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:${DB_OUTER_PORT}:${DB_PORT}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

volumes:
  mysql: