version: '3.7'
services:

  frontend:
    image: ${REGISTRY}/${FRONTEND_IMAGE}:${IMAGE_TAG}
    command: ["yarn", "run", "dev"]
    ports:
      - ${FRONTEND_PORT}:80
    volumes:
      - ${FRONTEND_PATH}:/app
    environment:
      APP_PORT: 80
      API_APP_URL: ${API_URL}
      WS_APP_URL: ${WS_URL}

  api:
    image: ${REGISTRY}/${API_IMAGE}:${IMAGE_TAG}
    ports:
      - ${API_PORT}:80
    volumes:
      - ${API_PATH}:/app
    environment:
      APP_PORT: 80
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGGING: ${TYPEORM_DB_LOGGING}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TOKEN_SECRET_WORD: ${JWT_SECRET_WORD}
      TOKEN_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    depends_on:
      - mariadb
      - redis

  api-cli:
    image: ${REGISTRY}/${API_CLI_IMAGE}:${IMAGE_TAG}
    volumes:
      - ${API_PATH}:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGGING: ${TYPEORM_DB_LOGGING}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    tty: true

  ws:
    image: ${REGISTRY}/${WS_IMAGE}:${IMAGE_TAG}
    command: ["yarn", "run", "start:dev"]
    ports:
      - ${WS_PORT}:80
    volumes:
      - ${WS_PATH}:/app
    environment:
      APP_PORT: 80
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGGING: ${TYPEORM_DB_LOGGING}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - mariadb
      - redis

  migrations:
    image: ${REGISTRY}/${MIGRATIONS_IMAGE}:${IMAGE_TAG}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./migrations:/app

  mariadb:
    image: mariadb:10.6.14
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_SOURCE_PATH}:/var/lib/mysql
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  redis:
    image: redis:7.0.0
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf