version: '3.7'
services:

  ws-node:
    image: ${REGISTRY}/todo-skill-up-ws-node:${IMAGE_TAG}
    ports:
      - "${WS_PORT}:3005"
    volumes:
      - "./websocket/nodeJs:/app"

  ws-node-cli:
    image: ${REGISTRY}/todo-skill-up-api-node-cli:${IMAGE_TAG}
    volumes:
      - "./websocket/nodeJs:/app"
    tty: true